### ISSUE TITLE
ImportError: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by Thuener** [Mogeng/IOHMM#23]
When using IOHMM with python 3.5.2 I get the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/tas/.local/lib/python3.5/site-packages/IOHMM/__init__.py", line 1, in <module>
>     from .IOHMM import (UnSupervisedIOHMM,
>   File "/home/tas/.local/lib/python3.5/site-packages/IOHMM/IOHMM.py", line 38, in <module>
>     from .forward_backward import forward_backward
>   File "/home/tas/.local/lib/python3.5/site-packages/IOHMM/forward_backward.py", line 21, in <module>
>     from scipy.misc import logsumexp
> ImportError: cannot import name 'logsumexp'

**Comment by coolsnake** [comment]
change to "from scipy.special import logsumexp"
