### ISSUE TITLE
SemiSupervisedIOHMM couldn't load model

### ISSUE THREAD

**Issue by Thuener** [Mogeng/IOHMM#24]
On line:
`SHMM_from_json = SemiSupervisedIOHMM.from_json(json_dict)`
i get the following error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-13-8fe9a1d9af1b> in <module>
> ----> 1 SHMM_from_json = SemiSupervisedIOHMM.from_json(json_dict)
> 
> ~/.local/lib/python3.5/site-packages/IOHMM/IOHMM.py in from_json(cls, json_dict)
>     539             model_initial=getattr(
>     540                 LinearModelLoader, json_dict['properties']['model_initial']['data_type']).from_json(
> --> 541                 json_dict['properties']['model_initial']),
>     542             model_transition=[getattr(
>     543                 LinearModelLoader, model_transition_json['data_type']
> 
> ~/.local/lib/python3.5/site-packages/IOHMM/linear_models.py in from_json(cls, json_dict)
>     316             l1_ratio=json_dict['properties']['l1_ratio'],
>     317             coef=np.load(json_dict['properties']['coef']['path']),
> --> 318             stderr=np.load(json_dict['properties']['stderr']['path']))
>     319 
>     320 
> 
> ~/.local/lib/python3.5/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
>     445             else:
>     446                 return format.read_array(fid, allow_pickle=allow_pickle,
> --> 447                                          pickle_kwargs=pickle_kwargs)
>     448         else:
>     449             # Try a pickle
> 
> ~/.local/lib/python3.5/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
>     694         # The array contained Python objects. We need to unpickle the data.
>     695         if not allow_pickle:
> --> 696             raise ValueError("Object arrays cannot be loaded when "
>     697                              "allow_pickle=False")
>     698         if pickle_kwargs is None:
> 
> ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by Thuener** [comment]
I try to change line 317 from IOHMM/linear_models.py to stderr=np.load(json_dict['properties']['stderr']['path']), allow_pickle=True) but the error persists.

**Comment by Mogeng** [comment]
Hi Thuener, thanks for reporting this! I searched a little bit and found this link: https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa. Can you try downgrading your numpy using `pip install numpy==1.16.2`? If it works, we can find some workaround. Thanks!

**Comment by Mogeng** [comment]
Solved in #32
