### ISSUE TITLE
What if some sequences has only one record in it?

### ISSUE THREAD

**Issue by Jasmine1004** [Mogeng/IOHMM#26]
I was using UnSupervisedIOHMM to learn sequences, but the `predict_log_proba` in `E_step` keeps give me **ValueError**: zero-size array to reduction operation maximum which has no identity. The error arises from `X = self._transform_X(X)` in `predict_log_proba` and my self.inp_transitions[seq]=[] due to the length of these sequences are 1. So they don't have inp_transitions. Is there any way I have get rid of this problem?

**Comment by Mogeng** [comment]
I think this only happens if all the sequences have length 1? If this is the case, there is no transition, you can simply use mixture model?
