### ISSUE TITLE
Using CrossEntropyMNL as model_emissions parameter

### ISSUE THREAD

**Issue by antonionieto** [Mogeng/IOHMM#27]
(UnSupervisedIOHMM)
When setting models as follows:

`SHMM.set_models(model_emissions = [CrossEntropyMNL(solver='lbfgs')], model_transition=CrossEntropyMNL(solver='lbfgs'), model_initial=CrossEntropyMNL(solver='lbfgs'))`

It throws me back this error:

> ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

It does not happen when I use instead:

`SHMM.set_models(model_emissions = [OLS(est_stderr=True)], model_transition=CrossEntropyMNL(solver='lbfgs'), model_initial=CrossEntropyMNL(solver='lbfgs'))`

Could you tell me how to face this problem?

Thanks in advanced!

P.D.: entire model adjustment code here:

`SHMM = UnSupervisedIOHMM(num_states=3, max_EM_iter=200, EM_tol=1e-4)`

`SHMM.set_models(model_emissions = [CrossEntropyMNL(solver='lbfgs')], model_transition=CrossEntropyMNL(solver='lbfgs'), model_initial=CrossEntropyMNL(solver='lbfgs'))`

`SHMM.set_inputs(covariates_initial = [], covariates_transition = ['var'], covariates_emissions = [['var']])`

`SHMM.set_outputs([['out']])`

`SHMM.set_data([df])`

`SHMM.train()`

**Comment by Mogeng** [comment]
Can you share the df or is there a minimal example of df that I can reproduce the error?

**Comment by antonionieto** [comment]
Sure! Here you have an example of df.

Thanks in advance!

[data.txt](https://github.com/Mogeng/IOHMM/files/4413111/data.txt)

**Comment by Mogeng** [comment]
It seems the output variable has negative value? CrossEntropyMNL deals with probability output  that are between 0 and 1.

**Comment by antonionieto** [comment]
Thanks! That was the problem.
