### ISSUE TITLE
Getting AIC/BIC to figure out the optimal states

### ISSUE THREAD

**Issue by sonam0125** [Mogeng/IOHMM#36]
Hi could you please let me know how can I get the AIC/BIC for UnSupervisedIOHMM to get the optimal hidden states.
Thank you for your help.

**Comment by Mogeng** [comment]
You probably want to use the formula here https://en.wikipedia.org/wiki/Bayesian_information_criterion. The log of the likelihood can directly come from SHMM.log_likelihood, after you finish training the model. The other parameters you should be able to count yourself.

**Comment by sonam0125** [comment]
Thank You.
